"""Added payment.currency

Revision ID: 16149372fccf
Revises: 1e939ac31001
Create Date: 2023-01-23 19:46:56.983461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16149372fccf'
down_revision = '1e939ac31001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.String(), nullable=True))
    op.execute("UPDATE payments SET currency='RUB'")
    op.alter_column('payments', 'currency', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
