"""Index for Employee.job

Revision ID: 6f071480699f
Revises: 16149372fccf
Create Date: 2023-01-24 01:18:52.024749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f071480699f'
down_revision = '16149372fccf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_employees_job'), 'employees', ['job'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_job'), table_name='employees')
    # ### end Alembic commands ###
